import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';

/// Application-owned localization table. Keeping product copy here avoids
/// platform-specific strings and makes iOS and Android render the same labels.
final class GeekPayLocalizations {
  const GeekPayLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('zh'),
    Locale('en'),
    Locale('ja'),
  ];

  static const LocalizationsDelegate<GeekPayLocalizations> delegate =
      _GeekPayLocalizationsDelegate();

  static GeekPayLocalizations of(BuildContext context) =>
      Localizations.of<GeekPayLocalizations>(context, GeekPayLocalizations) ??
      const GeekPayLocalizations(Locale('zh'));

  String get _language => switch (locale.languageCode) {
        'en' => 'en',
        'ja' => 'ja',
        _ => 'zh',
      };

  String t(String key) => _copy[_language]?[key] ?? _copy['zh']?[key] ?? key;

  String lastUpdated(String time) => switch (_language) {
        'en' => 'Updated $time',
        'ja' => '最終更新 $time',
        _ => '最近更新 $time',
      };

  String cardNumber(String value) => switch (_language) {
        'en' => 'No. $value',
        'ja' => 'No. $value',
        _ => 'No. $value',
      };

  String balanceAmount(String value) => switch (_language) {
        'en' => 'Balance $value',
        'ja' => '残高 $value',
        _ => '余额 $value',
      };

  String refreshIn(int seconds) => switch (_language) {
        'en' => 'Refreshes in $seconds s',
        'ja' => '$seconds秒後に更新',
        _ => '$seconds秒后刷新',
      };

  String maskedOpenId(String first, String last) => '$first****$last';

  String amountYuan(String value) => '¥$value';

  String transactionCount(int count) => switch (_language) {
        'en' => '$count transactions',
        'ja' => '$count件',
        _ => '$count 笔',
      };

  String fullDateTime(DateTime value) {
    final local = value.toLocal();
    String two(int part) => part.toString().padLeft(2, '0');
    final time = '${two(local.hour)}:${two(local.minute)}:${two(local.second)}';
    return switch (_language) {
      'en' => '${two(local.month)}/${two(local.day)}/${local.year} $time',
      'ja' => '${local.year}/${two(local.month)}/${two(local.day)} $time',
      _ => '${local.year}-${two(local.month)}-${two(local.day)} $time',
    };
  }

  String dateRangeDays(DateTime start, DateTime end) {
    String two(int part) => part.toString().padLeft(2, '0');
    return switch (_language) {
      'en' => '${two(start.month)}/${two(start.day)} to '
          '${two(end.month)}/${two(end.day)}',
      'ja' => '${two(start.month)}/${two(start.day)}〜'
          '${two(end.month)}/${two(end.day)}',
      _ => '${start.month}月${start.day}日 至 ${end.month}月${end.day}日',
    };
  }

  static const Map<String, Map<String, String>> _copy = {
    'zh': {
      'widgetTitle': '消费码',
      'widgetSubtitle': '支付一触即达',
      'addPayWidget': '添加消费码小组件',
      'addToHomeScreen': '添加到主屏幕',
      'widgetGuideSummary': '将消费码放到主屏幕，轻触小组件即可打开。',
      'widgetGuideSteps': '手动添加步骤',
      'widgetConfirmAdd': '请在系统弹窗中确认添加。',
      'widgetManualFallback': '当前桌面未接受添加请求，请按下方步骤手动添加。',
      'widgetUnsupported': '此系统暂不支持主屏幕小组件。iPhone 需要 iOS 14 或更新版本。',
      'widgetIosStep1': '回到主屏幕，长按空白处，轻点“编辑”或左上角的“+”。',
      'widgetIosStep2': '选择“添加小组件”，搜索 TechPie，再选择“消费码”。',
      'widgetIosStep3': '轻点“添加小组件”，放到合适的位置后点“完成”。',
      'widgetAndroidStep1': '回到主屏幕，长按空白处，打开“小组件”。',
      'widgetAndroidStep2': '找到 TechPie，长按“消费码”小组件并拖到主屏幕。',
      'widgetAndroidStep3': '放到合适的位置；以后轻触小组件即可打开消费码。',
      'appName': 'GeekPay',
      'campusPay': '校园支付',
      'continue': '继续',
      'getStarted': '开始使用',
      'back': '返回',
      'close': '关闭',
      'cancel': '取消',
      'confirm': '确认',
      'done': '完成',
      'retry': '重试',
      'loading': '正在加载',
      'save': '保存',
      'edit': '修改',
      'delete': '删除',
      'notAvailable': '服务暂未开放',
      'welcomeTitle': '把 eCard 装进 GeekPay',
      'welcomeBody': '出示付款码、扫一扫、查看账单和管理 eCard，一切都集中在一个清晰安全的空间里。',
      'privacyTitle': '你的身份只属于你',
      'privacyBody':
          'OpenID 只用于建立校园支付会话，并保存在系统安全存储中。标准构建不会输出完整身份标识；显式启用的调试追踪除外。',
      'openidTitle': '设置你的 OpenID',
      'openidBody': '输入学校提供的微信 OpenID。登录后可在卡片信息中修改，修改会重新建立完整会话。',
      'accountSetupTitle': '连接 eCard',
      'accountSetupBody':
          '请在 TechPie 的 Account 设置中配置 OPENID。eCard 会自动使用该账号建立会话。',
      'openAccountSettings': '打开 Account 设置',
      'openid': 'OPENID',
      'openidPlaceholder': '输入 OpenID',
      'showOpenId': '显示 OpenID',
      'hideOpenId': '隐藏 OpenID',
      'openidEmpty': '请输入 OpenID',
      'openidWhitespace': 'OpenID 不能包含空格',
      'openidTooShort': 'OpenID 长度不足 16 位',
      'openidTooLong': 'OpenID 长度不能超过 256 位',
      'signingIn': '正在安全登录…',
      'signInFailed': '无法登录，请检查网络或 OpenID 后重试。',
      'secureSession': '会话由校园支付服务签发并经过身份一致性校验。',
      'wallet': '钱包',
      'campusCard': '上海科技大学 eCard',
      'campusCardShort': 'eCard',
      'balance': '余额',
      'presentToReader': '出示付款码或靠近读卡设备',
      'showPaymentCode': '付款码',
      'scanToPay': '扫一扫',
      'cardUnavailable': '当前卡片状态无法付款',
      'bindCard': '绑定卡片',
      'cardDetails': '卡片信息',
      'more': '更多',
      'onlineCode': '在线付款码',
      'offlineCode': '离线付款码',
      'offlineAuthorizationBannerPrompt': '开通离线付款码，以便在网络不稳定时继续支付。',
      'switchOnline': '切换在线付款码',
      'switchOffline': '切换离线付款码',
      'touchToRefresh': '轻触二维码刷新',
      'paymentCodeLoading': '正在生成付款码…',
      'paymentCodeFailed': '付款码生成失败',
      'networkOnline': '网络正常',
      'networkDisconnected': '网络已断开',
      'networkApiError': '服务响应异常',
      'networkChecking': '正在检测',
      'onlineStatus': '在线状态',
      'requestLatency': '当前延迟',
      'manualOfflineActive': '手动离线模式会保持到 App 进程退出。',
      'automaticOfflineMode': '网络异常时自动使用离线码，恢复后自动返回在线码。',
      'activationRequired': '需要先开通付款码',
      'activate': '立即开通',
      'paymentSucceeded': '支付成功',
      'localConfirmedAt': '本机确认时间',
      'merchant': '商户',
      'terminal': '终端',
      'order': '订单',
      'recentActivity': '最近使用',
      'allActivity': '查看全部',
      'noTransactions': '这个时间范围内没有交易',
      'noDateRange': '不指定日期',
      'startDate': '开始日期',
      'endDate': '结束日期',
      'to': '至',
      'loadMore': '加载更多',
      'transactionDetails': '交易详情',
      'transactionType': '交易类型',
      'transactionId': '交易流水号',
      'merchantNumber': '商户号',
      'posCode': 'POS 代码',
      'room': '场所',
      'location': '交易地点',
      'channel': '交易渠道',
      'additionalInformation': '附加信息',
      'information': '信息',
      'activity': '使用明细',
      'name': '姓名',
      'identity': '身份',
      'department': '所属单位',
      'status': '账户状态',
      'validUntil': '有效期',
      'lastLogin': '最近登录',
      'normal': '正常',
      'recharge': '充值',
      'security': '安全中心',
      'settings': '设置',
      'removeCard': '解绑卡片',
      'signOut': '退出登录',
      'allowNotifications': '允许通知',
      'paymentCodeEnabled': '启用付款码',
      'dateRange': '日期范围',
      'last30Days': '最近 30 天',
      'thisMonth': '本月',
      'customRange': '自定义',
      'billLoadFailed': '账单信息加载失败',
      'spending': '消费',
      'recharged': '充值',
      'rechargeTitle': '充值',
      'rechargeAmount': '充值金额',
      'remainingBalance': '当前余额',
      'addFunds': '充值',
      'minimumRecharge': '最低充值 1 元，最高 1000 元',
      'rechargeUnavailable': '当前账户没有可用充值渠道',
      'pay': 'Pay',
      'payWith': '付款卡片',
      'payee': '收款方',
      'confirmPayment': '确认付款',
      'enterPassword': '输入 6 位消费密码',
      'password': '消费密码',
      'scanAgain': '重新扫码',
      'recognitionFailed': '识别失败',
      'attendanceSucceeded': '签到成功',
      'deviceOpened': '开阀成功',
      'trayBound': '绑盘成功',
      'processed': '处理完成',
      'fee': '含管理费',
      'postBalance': '交易后余额',
      'oldPassword': '原密码',
      'newPassword': '新密码',
      'confirmPassword': '再次输入新密码',
      'lost': '挂失',
      'frozen': '冻结',
      'closed': '销户',
      'preclosed': '预销户',
      'cardNumberField': '卡号',
      'queryPassword': '查询密码（6 位数字）',
      'documentType': '证件类型',
      'documentNumber': '证件号',
      'phoneNumber': '手机号',
      'nationalId': '居民身份证',
      'militaryId': '军人证件',
      'passport': '护照',
      'workId': '工作证',
      'confirmBind': '确认绑定',
      'bindFailed': '绑定失败，请核对信息后重试',
      'fieldRequired': '请填写完整信息',
      'sixDigitsRequired': '请输入 6 位数字',
      'unbindTitle': '解除卡片绑定',
      'unbindWarning': '解绑会清除本机会话、个人缓存、离线授权与密钥。此操作不可撤销。',
      'ackUnbind': '我已了解解绑的全部影响',
      'confirmUnbind': '确认解绑',
      'unbindFailed': '解绑失败，请稍后重试',
      'torch': '手电筒',
      'photoLibrary': '相册',
      'alignQrCode': '将二维码放入框内',
      'scannerUnavailable': '相机不可用',
      'cameraUnavailableHint': '当前设备没有可用相机，请从相册选择二维码图片。',
      'offlineAuthorization': '离线授权',
      'remainingUses': '剩余次数',
      'opened': '已开通',
      'notOpened': '未开通',
      'expiresOn': '到期日',
      'renew': '续期',
      'removeFromDevice': '移除此设备',
      'language': '语言',
      'systemLanguage': '跟随系统',
      'simplifiedChinese': '简体中文',
      'english': 'English',
      'japanese': '日本語',
      'limits': '消费限额',
      'changePassword': '修改消费密码',
      'passwordChanged': '消费密码修改成功',
      'perTransaction': '单笔限额',
      'perDay': '单日限额',
      'cardSpendingLimits': '卡消费限额',
      'qrSpendingLimits': '二维码消费限额',
      'limitsChanged': '消费限额修改成功',
      'invalidLimits': '请输入有效金额，单日限额不能低于单笔限额；二维码限额还需要 6 位消费密码。',
      'debugMode': '调试模式',
      'skipScanConfirmation': '小额免密扫码跳过确认',
      'confirmScanPayment': '是否继续扫码交易？',
      'confirmScanPaymentDescription': '继续后才会向校园支付服务提交二维码。',
      'debugPaymentSuccess': '调试：触发支付成功',
      'about': '关于 GeekPay',
      'clientOnlyRemoveNotice': '此操作只删除本机离线授权，不会在服务端吊销。',
    },
    'en': {
      'widgetTitle': 'Pay Code',
      'widgetSubtitle': 'Pay in a tap',
      'addPayWidget': 'Add Pay Code Widget',
      'addToHomeScreen': 'Add to Home Screen',
      'widgetGuideSummary':
          'Keep your Pay Code on the Home Screen. Tap the widget to open it.',
      'widgetGuideSteps': 'Add it manually',
      'widgetConfirmAdd': 'Confirm Add in the system dialog.',
      'widgetManualFallback':
          'The launcher did not accept the request. Follow the steps below to add it manually.',
      'widgetUnsupported':
          'Home Screen widgets are unavailable on this system. iPhone requires iOS 14 or later.',
      'widgetIosStep1':
          'On the Home Screen, touch and hold an empty area, then tap Edit or the + button.',
      'widgetIosStep2':
          'Choose Add Widget, search for TechPie, then select Pay Code.',
      'widgetIosStep3':
          'Tap Add Widget, place it where you want, then tap Done.',
      'widgetAndroidStep1':
          'On the Home Screen, touch and hold an empty area, then open Widgets.',
      'widgetAndroidStep2':
          'Find TechPie. Touch and hold Pay Code, then drag it onto the Home Screen.',
      'widgetAndroidStep3':
          'Place the widget where you want. Tap it whenever you need your Pay Code.',
      'appName': 'GeekPay',
      'campusPay': 'Campus Pay',
      'continue': 'Continue',
      'getStarted': 'Get Started',
      'back': 'Back',
      'close': 'Close',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'done': 'Done',
      'retry': 'Try Again',
      'loading': 'Loading',
      'save': 'Save',
      'edit': 'Edit',
      'delete': 'Delete',
      'notAvailable': 'Service not available',
      'welcomeTitle': 'Your eCard, in GeekPay',
      'welcomeBody':
          'Present a payment code, scan to pay, review activity, and manage your eCard in one clear and secure place.',
      'privacyTitle': 'Your identity stays yours',
      'privacyBody':
          'Your OpenID establishes the campus payment session and stays in secure system storage. Standard builds do not log it; explicitly enabled debug tracing is the exception.',
      'openidTitle': 'Set your OpenID',
      'openidBody':
          'Enter the WeChat OpenID supplied by the university. You can change it later in Card Information; doing so creates a new session.',
      'accountSetupTitle': 'Connect eCard',
      'accountSetupBody':
          'Configure OPENID in TechPie Account settings. eCard will use that account automatically.',
      'openAccountSettings': 'Open Account Settings',
      'openid': 'OPENID',
      'openidPlaceholder': 'Enter OpenID',
      'showOpenId': 'Show OpenID',
      'hideOpenId': 'Hide OpenID',
      'openidEmpty': 'Enter your OpenID',
      'openidWhitespace': 'OpenID cannot contain spaces',
      'openidTooShort': 'OpenID must be at least 16 characters',
      'openidTooLong': 'OpenID cannot exceed 256 characters',
      'signingIn': 'Signing in securely…',
      'signInFailed':
          'Unable to sign in. Check your network and OpenID, then try again.',
      'secureSession':
          'The campus payment service issues the session and GeekPay verifies its identity.',
      'wallet': 'Wallet',
      'campusCard': 'ShanghaiTech University eCard',
      'campusCardShort': 'eCard',
      'balance': 'Balance',
      'presentToReader': 'Present a payment code or hold near a reader',
      'showPaymentCode': 'Pay Code',
      'scanToPay': 'Scan',
      'cardUnavailable': 'This card cannot be used for payment',
      'bindCard': 'Bind Card',
      'cardDetails': 'Card Information',
      'more': 'More',
      'onlineCode': 'Online Code',
      'offlineCode': 'Offline Code',
      'offlineAuthorizationBannerPrompt':
          'Set up offline payment so you can keep paying when the network is unstable.',
      'switchOnline': 'Use Online Code',
      'switchOffline': 'Use Offline Code',
      'touchToRefresh': 'Tap the code to refresh',
      'paymentCodeLoading': 'Generating payment code…',
      'paymentCodeFailed': 'Unable to generate code',
      'networkOnline': 'Online',
      'networkDisconnected': 'Disconnected',
      'networkApiError': 'Service response error',
      'networkChecking': 'Checking',
      'onlineStatus': 'Online Status',
      'requestLatency': 'Current Latency',
      'manualOfflineActive':
          'Manual offline mode remains active until the app process exits.',
      'automaticOfflineMode':
          'Offline code is selected automatically on failure and disabled after recovery.',
      'activationRequired': 'Payment code setup is required',
      'activate': 'Set Up Now',
      'paymentSucceeded': 'Payment Complete',
      'localConfirmedAt': 'Confirmed on this device',
      'merchant': 'Merchant',
      'terminal': 'Terminal',
      'order': 'Order',
      'recentActivity': 'Recent Activity',
      'allActivity': 'See All',
      'noTransactions': 'No transactions in this date range',
      'noDateRange': 'No Date Range',
      'startDate': 'Start Date',
      'endDate': 'End Date',
      'to': 'to',
      'loadMore': 'Load More',
      'transactionDetails': 'Transaction Details',
      'transactionType': 'Transaction Type',
      'transactionId': 'Transaction ID',
      'merchantNumber': 'Merchant Number',
      'posCode': 'POS Code',
      'room': 'Place',
      'location': 'Location',
      'channel': 'Channel',
      'additionalInformation': 'Additional Information',
      'information': 'Information',
      'activity': 'Activity',
      'name': 'Name',
      'identity': 'Identity',
      'department': 'Department',
      'status': 'Account Status',
      'validUntil': 'Valid Until',
      'lastLogin': 'Last Login',
      'normal': 'Active',
      'recharge': 'Add Money',
      'security': 'Security',
      'settings': 'Settings',
      'removeCard': 'Unbind Card',
      'signOut': 'Sign Out',
      'allowNotifications': 'Allow Notifications',
      'paymentCodeEnabled': 'Enable Payment Code',
      'dateRange': 'Date Range',
      'last30Days': 'Last 30 Days',
      'thisMonth': 'This Month',
      'customRange': 'Custom',
      'billLoadFailed': 'Unable to Load Bill Information',
      'spending': 'Spent',
      'recharged': 'Added',
      'rechargeTitle': 'Add Money',
      'rechargeAmount': 'Amount',
      'remainingBalance': 'Current Balance',
      'addFunds': 'Add',
      'minimumRecharge': 'Minimum ¥1, maximum ¥1,000',
      'rechargeUnavailable':
          'No recharge channel is available for this account',
      'pay': 'Pay',
      'payWith': 'Paying With',
      'payee': 'Payee',
      'confirmPayment': 'Confirm Payment',
      'enterPassword': 'Enter the 6-digit payment password',
      'password': 'Payment Password',
      'scanAgain': 'Scan Again',
      'recognitionFailed': 'Unable to Recognize Code',
      'attendanceSucceeded': 'Check-in Complete',
      'deviceOpened': 'Device Opened',
      'trayBound': 'Tray Bound',
      'processed': 'Complete',
      'fee': 'Fee',
      'postBalance': 'Balance After Transaction',
      'oldPassword': 'Current Password',
      'newPassword': 'New Password',
      'confirmPassword': 'Confirm New Password',
      'lost': 'Reported Lost',
      'frozen': 'Frozen',
      'closed': 'Closed',
      'preclosed': 'Closing',
      'cardNumberField': 'Card Number',
      'queryPassword': '6-digit Query Password',
      'documentType': 'Document Type',
      'documentNumber': 'Document Number',
      'phoneNumber': 'Phone Number',
      'nationalId': 'National ID',
      'militaryId': 'Military ID',
      'passport': 'Passport',
      'workId': 'Work ID',
      'confirmBind': 'Bind Card',
      'bindFailed':
          'Unable to bind the card. Check the information and try again.',
      'fieldRequired': 'Complete all required fields',
      'sixDigitsRequired': 'Enter 6 digits',
      'unbindTitle': 'Unbind Card',
      'unbindWarning':
          'Unbinding clears this device’s session, cached profile, offline authorization, and keys. This cannot be undone.',
      'ackUnbind': 'I understand the effects of unbinding',
      'confirmUnbind': 'Unbind Card',
      'unbindFailed': 'Unable to unbind the card. Try again later.',
      'torch': 'Flashlight',
      'photoLibrary': 'Photos',
      'alignQrCode': 'Position the QR code inside the frame',
      'scannerUnavailable': 'Camera unavailable',
      'cameraUnavailableHint':
          'No camera is available on this device. Choose a QR code from Photos.',
      'offlineAuthorization': 'Offline Authorization',
      'remainingUses': 'Uses Remaining',
      'opened': 'Enabled',
      'notOpened': 'Not Enabled',
      'expiresOn': 'Expires',
      'renew': 'Renew',
      'removeFromDevice': 'Remove from This Device',
      'language': 'Language',
      'systemLanguage': 'System Default',
      'simplifiedChinese': '简体中文',
      'english': 'English',
      'japanese': '日本語',
      'limits': 'Spending Limits',
      'changePassword': 'Change Payment Password',
      'passwordChanged': 'Payment password changed',
      'perTransaction': 'Per Transaction',
      'perDay': 'Daily Limit',
      'cardSpendingLimits': 'Card Spending Limits',
      'qrSpendingLimits': 'QR Code Spending Limits',
      'limitsChanged': 'Spending limits changed',
      'invalidLimits':
          'Enter valid amounts. The daily limit cannot be below the per-transaction limit. QR limits also require a 6-digit payment password.',
      'debugMode': 'Debug Mode',
      'skipScanConfirmation': 'Skip Scan Confirmation',
      'confirmScanPayment': 'Continue this scan payment?',
      'confirmScanPaymentDescription':
          'The QR code is submitted only after you continue.',
      'debugPaymentSuccess': 'Debug: Trigger Payment Success',
      'about': 'About GeekPay',
      'clientOnlyRemoveNotice':
          'This removes the offline authorization from this device only. It does not revoke it on the server.',
    },
    'ja': {
      'widgetTitle': '支払いコード',
      'widgetSubtitle': 'タップで支払い',
      'addPayWidget': '支払いウィジェットを追加',
      'addToHomeScreen': 'ホーム画面に追加',
      'widgetGuideSummary': 'ホーム画面のウィジェットをタップして支払いコードを開けます。',
      'widgetGuideSteps': '手動で追加する手順',
      'widgetConfirmAdd': 'システムのダイアログで追加を確認してください。',
      'widgetManualFallback': '追加リクエストが受け付けられませんでした。以下の手順で追加してください。',
      'widgetUnsupported':
          'このシステムではホーム画面ウィジェットを利用できません。iPhone は iOS 14 以降が必要です。',
      'widgetIosStep1': 'ホーム画面の空白部分を長押しし、「編集」または「+」をタップします。',
      'widgetIosStep2': '「ウィジェットを追加」で TechPie を検索し、支払いコードを選びます。',
      'widgetIosStep3': '「ウィジェットを追加」をタップして配置し、「完了」をタップします。',
      'widgetAndroidStep1': 'ホーム画面の空白部分を長押しし、ウィジェットを開きます。',
      'widgetAndroidStep2': 'TechPie の支払いコードを長押ししてホーム画面へドラッグします。',
      'widgetAndroidStep3': '好きな位置に置きます。ウィジェットをタップすると支払いコードが開きます。',
      'appName': 'GeekPay',
      'campusPay': 'キャンパス決済',
      'continue': '続ける',
      'getStarted': 'はじめる',
      'back': '戻る',
      'close': '閉じる',
      'cancel': 'キャンセル',
      'confirm': '確認',
      'done': '完了',
      'retry': 'もう一度試す',
      'loading': '読み込み中',
      'save': '保存',
      'edit': '変更',
      'delete': '削除',
      'notAvailable': '現在利用できません',
      'welcomeTitle': 'eCard を GeekPay に',
      'welcomeBody': '支払いコード、スキャン、利用明細、eCard 管理を、ひとつのわかりやすく安全な場所にまとめます。',
      'privacyTitle': 'あなたの識別情報は、あなたのもの',
      'privacyBody':
          'OpenID はキャンパス決済セッションの確立に使われ、安全な領域に保存されます。通常ビルドでは記録せず、明示的なデバッグ追跡だけが例外です。',
      'openidTitle': 'OpenID を設定',
      'openidBody':
          '大学から提供された WeChat OpenID を入力してください。カード情報から後で変更でき、変更時はセッションを再作成します。',
      'accountSetupTitle': 'eCard を接続',
      'accountSetupBody':
          'TechPie の Account 設定で OPENID を設定してください。eCard はそのアカウントを自動的に使用します。',
      'openAccountSettings': 'Account 設定を開く',
      'openid': 'OPENID',
      'openidPlaceholder': 'OpenID を入力',
      'showOpenId': 'OpenID を表示',
      'hideOpenId': 'OpenID を隠す',
      'openidEmpty': 'OpenID を入力してください',
      'openidWhitespace': 'OpenID に空白は使用できません',
      'openidTooShort': 'OpenID は16文字以上必要です',
      'openidTooLong': 'OpenID は256文字以内で入力してください',
      'signingIn': '安全にログインしています…',
      'signInFailed': 'ログインできません。ネットワークと OpenID を確認して、もう一度お試しください。',
      'secureSession': 'セッションはキャンパス決済サービスが発行し、GeekPay が本人情報を照合します。',
      'wallet': 'ウォレット',
      'campusCard': '上海科技大学 eCard',
      'campusCardShort': 'eCard',
      'balance': '残高',
      'presentToReader': '支払いコードを表示するか、リーダーにかざしてください',
      'showPaymentCode': '支払いコード',
      'scanToPay': 'スキャン',
      'cardUnavailable': 'このカードは現在支払いに使えません',
      'bindCard': 'カードを登録',
      'cardDetails': 'カード情報',
      'more': 'その他',
      'onlineCode': 'オンラインコード',
      'offlineCode': 'オフラインコード',
      'offlineAuthorizationBannerPrompt': 'ネットワークが不安定なときも支払えるよう、オフライン決済を設定します。',
      'switchOnline': 'オンラインに切り替え',
      'switchOffline': 'オフラインに切り替え',
      'touchToRefresh': 'コードをタップして更新',
      'paymentCodeLoading': '支払いコードを作成中…',
      'paymentCodeFailed': 'コードを作成できません',
      'networkOnline': 'オンライン',
      'networkDisconnected': 'オフライン',
      'networkApiError': 'サービス応答異常',
      'networkChecking': '確認中',
      'onlineStatus': 'オンライン状態',
      'requestLatency': '現在の遅延',
      'manualOfflineActive': '手動オフラインモードは App を終了するまで維持されます。',
      'automaticOfflineMode': '異常時は自動でオフラインコードに切り替え、復旧後はオンラインに戻ります。',
      'activationRequired': '支払いコードの設定が必要です',
      'activate': '今すぐ設定',
      'paymentSucceeded': '支払い完了',
      'localConfirmedAt': 'この端末での確認時刻',
      'merchant': '加盟店',
      'terminal': '端末',
      'order': '注文',
      'recentActivity': '最近のご利用',
      'allActivity': 'すべて表示',
      'noTransactions': 'この期間の利用はありません',
      'noDateRange': '日付を指定しない',
      'startDate': '開始日',
      'endDate': '終了日',
      'to': 'から',
      'loadMore': 'さらに読み込む',
      'transactionDetails': '取引の詳細',
      'transactionType': '取引種別',
      'transactionId': '取引番号',
      'merchantNumber': '加盟店番号',
      'posCode': 'POSコード',
      'room': '場所',
      'location': '取引場所',
      'channel': '取引チャネル',
      'additionalInformation': '追加情報',
      'information': '情報',
      'activity': 'ご利用明細',
      'name': '氏名',
      'identity': '身分',
      'department': '所属',
      'status': 'アカウント状態',
      'validUntil': '有効期限',
      'lastLogin': '最終ログイン',
      'normal': '正常',
      'recharge': 'チャージ',
      'security': 'セキュリティ',
      'settings': '設定',
      'removeCard': 'カード登録を解除',
      'signOut': 'サインアウト',
      'allowNotifications': '通知を許可',
      'paymentCodeEnabled': '支払いコードを有効にする',
      'dateRange': '期間',
      'last30Days': '過去30日',
      'thisMonth': '今月',
      'customRange': 'カスタム',
      'billLoadFailed': '請求情報を読み込めません',
      'spending': '利用額',
      'recharged': 'チャージ額',
      'rechargeTitle': 'チャージ',
      'rechargeAmount': 'チャージ金額',
      'remainingBalance': '現在の残高',
      'addFunds': '追加する',
      'minimumRecharge': '最低1元、最高1,000元',
      'rechargeUnavailable': 'このアカウントで利用できるチャージ方法がありません',
      'pay': 'Pay',
      'payWith': '支払いカード',
      'payee': '支払先',
      'confirmPayment': '支払いを確認',
      'enterPassword': '6桁の支払いパスワードを入力',
      'password': '支払いパスワード',
      'scanAgain': 'もう一度スキャン',
      'recognitionFailed': 'コードを認識できません',
      'attendanceSucceeded': 'チェックイン完了',
      'deviceOpened': '開放しました',
      'trayBound': 'トレイを登録しました',
      'processed': '処理完了',
      'fee': '手数料',
      'postBalance': '取引後残高',
      'oldPassword': '現在のパスワード',
      'newPassword': '新しいパスワード',
      'confirmPassword': '新しいパスワードを再入力',
      'lost': '紛失届済み',
      'frozen': '停止中',
      'closed': '解約済み',
      'preclosed': '解約手続き中',
      'cardNumberField': 'カード番号',
      'queryPassword': '6桁の照会パスワード',
      'documentType': '本人確認書類',
      'documentNumber': '書類番号',
      'phoneNumber': '電話番号',
      'nationalId': '身分証明書',
      'militaryId': '軍人証',
      'passport': 'パスポート',
      'workId': '職員証',
      'confirmBind': 'カードを登録',
      'bindFailed': 'カードを登録できません。入力内容を確認して、もう一度お試しください。',
      'fieldRequired': '必須項目をすべて入力してください',
      'sixDigitsRequired': '6桁の数字を入力してください',
      'unbindTitle': 'カード登録を解除',
      'unbindWarning': '解除すると、この端末のセッション、プロフィールキャッシュ、オフライン認証、鍵が削除されます。元に戻せません。',
      'ackUnbind': '登録解除の影響を理解しました',
      'confirmUnbind': '登録を解除',
      'unbindFailed': '登録を解除できません。しばらくしてからもう一度お試しください。',
      'torch': 'フラッシュライト',
      'photoLibrary': '写真',
      'alignQrCode': 'QRコードを枠内に合わせてください',
      'scannerUnavailable': 'カメラを利用できません',
      'cameraUnavailableHint': 'このデバイスではカメラを利用できません。写真から QR コードを選択してください。',
      'offlineAuthorization': 'オフライン認証',
      'remainingUses': '残り回数',
      'opened': '開通済み',
      'notOpened': '未開通',
      'expiresOn': '有効期限',
      'renew': '更新',
      'removeFromDevice': 'このデバイスから削除',
      'language': '言語',
      'systemLanguage': 'システム設定',
      'simplifiedChinese': '简体中文',
      'english': 'English',
      'japanese': '日本語',
      'limits': '利用限度額',
      'changePassword': '支払いパスワードを変更',
      'passwordChanged': '支払いパスワードを変更しました',
      'perTransaction': '1回あたり',
      'perDay': '1日あたり',
      'cardSpendingLimits': 'カード利用限度額',
      'qrSpendingLimits': 'QRコード利用限度額',
      'limitsChanged': '利用限度額を変更しました',
      'invalidLimits':
          '有効な金額を入力してください。1日限度額は1回限度額以上にし、QR限度額には6桁の支払いパスワードも必要です。',
      'debugMode': 'デバッグモード',
      'skipScanConfirmation': '少額スキャン確認を省略',
      'confirmScanPayment': 'スキャン取引を続行しますか？',
      'confirmScanPaymentDescription': '続行した後にのみQRコードを送信します。',
      'debugPaymentSuccess': 'デバッグ：支払い成功を再現',
      'about': 'GeekPay について',
      'clientOnlyRemoveNotice': 'このデバイスのオフライン認証だけを削除します。サーバー側では取り消されません。',
    },
  };
}

extension GeekPayLocalizationContext on BuildContext {
  GeekPayLocalizations get l10n => GeekPayLocalizations.of(this);
}

final class _GeekPayLocalizationsDelegate
    extends LocalizationsDelegate<GeekPayLocalizations> {
  const _GeekPayLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => GeekPayLocalizations.supportedLocales.any(
        (supported) => supported.languageCode == locale.languageCode,
      );

  @override
  Future<GeekPayLocalizations> load(Locale locale) =>
      SynchronousFuture(GeekPayLocalizations(locale));

  @override
  bool shouldReload(_GeekPayLocalizationsDelegate old) => false;
}
